
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Integration API Lambda Function deployment template.

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  APIFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: HttpApi 
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: latest
      DockerContext: ./
      Dockerfile: lambda.Dockerfile
